name: Claude Research Test

on:
  workflow_dispatch:

jobs:
  research:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone openstates/people repository
      run: |
        git clone https://github.com/openstates/people.git openstates-people
    
    - name: Install Claude CLI
      run: |
        npm install -g @anthropic-ai/claude-code
        echo "Claude CLI installed, checking version..."
        claude --version || echo "Claude version check failed"
        echo "Checking if Claude CLI is in PATH..."
        which claude || echo "Claude not found in PATH"
    
    - name: Claude Hello World
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        #!/bin/bash
        set -e
        
        
        echo "Researching Katie Britt's donors"
        
        # Katie Britt donor research prompt
        full_prompt="Research Senator Katie Britt's top campaign donors and contributors. Search specifically on these sites:
        1. OpenSecrets.org - for her donor data and industry contributions
        2. FEC.gov - for official campaign finance filings
        3. Senate.gov lobbying disclosure - for lobbying connections
        
        Find:
        - Top corporate donors with specific dollar amounts and cycles
        - Top contributing industries with totals
        - Major PAC and special interest group contributions
        - Any notable lobbying connections or revolving door relationships
        
        Provide direct links to the specific pages where you found this data on OpenSecrets.org, FEC.gov, and Senate lobbying disclosure databases."
        
        # Use Claude CLI with --print flag for non-interactive output
        echo "=== SENDING PROMPT TO CLAUDE ==="
        echo "Prompt: $full_prompt"
        echo "=== CLAUDE OUTPUT ==="
        echo "$full_prompt" | claude --print
        echo "=== END CLAUDE OUTPUT ==="