name: Claude Research Test

on:
  workflow_dispatch:

jobs:
  research:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone openstates/people repository
      run: |
        git clone https://github.com/openstates/people.git openstates-people
    
    - name: Install Claude CLI
      run: |
        npm install -g @anthropic-ai/claude-code
    
    - name: Research Katie Britt
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        #!/bin/bash
        set -e
        
        # Hardcoded for Katie Britt
        yaml_file="openstates-people/data/us/legislature/Katie-Boyd-Britt-7bf077d8-e8b9-503e-b9c2-d18b55951e93.yml"
        
        if [ ! -f "$yaml_file" ]; then
          echo "Katie Britt YAML file not found: $yaml_file"
          exit 1
        fi
        
        echo "Researching Katie Britt"
        
        # Create research prompt with legislator data
        full_prompt="Here is legislator data from OpenStates:
        
        $(cat "$yaml_file")
        
        IMPORTANT: You MUST use web search to find current information about Katie Britt (Senator from Alabama). Search for:
        1. Her official Senate website and campaign website
        2. Her positions on key issues  
        3. Her recent campaign finance data from OpenSecrets.org or FEC filings
        4. Her top donors and industry contributions
        
        Research Katie Britt's campaign website and find her issues as an array with title/description. Also find her top donors by industry/corporation as an array with donor name, potential issue they care about, and money donated. Output as JSON.
        
        Use web search tools to gather this information before responding. Do not make up or guess at information."
        
        # Use Claude CLI and echo output
        echo "=== CLAUDE OUTPUT ==="
        echo "$full_prompt" | claude
        echo "=== END CLAUDE OUTPUT ==="