name: Claude Research Test

on:
  workflow_dispatch:

jobs:
  research:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Clone openstates/people repository
      run: |
        git clone https://github.com/openstates/people.git openstates-people
    
    - name: Install Claude CLI
      run: |
        npm install -g @anthropic-ai/claude-code
        echo "Claude CLI installed, checking version..."
        claude --version || echo "Claude version check failed"
        echo "Checking if Claude CLI is in PATH..."
        which claude || echo "Claude not found in PATH"
    
    - name: Research Katie Britt
      env:
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      run: |
        #!/bin/bash
        set -e
        
        
        echo "Testing Claude with simple prompt"
        
        # Simple hello world prompt
        full_prompt="Hello Claude! Please respond with 'Hello World' and tell me what 2+2 equals."
        
        # Debug: Check if Claude CLI is working
        echo "Testing Claude CLI..."
        echo "Hello Claude" | claude --help || echo "Claude help failed"
        
        # Use Claude CLI with timeout and echo output
        echo "=== SENDING PROMPT TO CLAUDE ==="
        echo "Prompt length: $(echo "$full_prompt" | wc -c) characters"
        echo "=== CLAUDE OUTPUT ==="
        timeout 300 bash -c 'echo "$0" | claude' "$full_prompt" || echo "Claude command timed out or failed"
        echo "=== END CLAUDE OUTPUT ==="