name: Enhanced Legislator Research
on:
  workflow_dispatch:
    inputs:
      locale:
        description: "Locale to process (e.g., 'ak', 'tx', 'us' or leave empty for all)"
        required: false
        default: "us"
        type: string
      max_people:
        description: "Maximum number of people to process"
        required: false
        default: "10"
        type: string
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"

jobs:
  research:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout OpenStates People Repo
        run: |
          git clone https://github.com/openstates/people.git openstates-people

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Research People (Enhanced with Web Search)
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          LOCALE: ${{ github.event.inputs.locale }}
          MAX_PEOPLE: ${{ github.event.inputs.max_people }}
        run: |
          # Uses enhanced researcher with web search capabilities for accurate donor data
          python scripts/enhanced_simple_researcher.py openstates-people .

      - name: Commit Results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Add all new research files
          git add data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No new research data to commit"
          else
            git commit -m "Add enhanced research data with accurate donor information for $(date +%Y-%m-%d)"
            git push origin main
          fi
